<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <AssemblyName>GlutenFree.OddJob</AssemblyName>
    
    <Description>Core Model and Functionality for Job Creation and Job Running.</Description>
    <PackageTags>job jobs jobscheduler scheduler oddjob task future later</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>
</Project>
